version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: shortlink-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shortlink
      MYSQL_USER: app
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"

  redis:
    image: redis:7
    container_name: shortlink-redis
    restart: always
    ports:
      - "6479:6379"
volumes:
  mysql_data:
